import path from 'path';

export const SCRAPE_CONFIG = {
  QUARTERLY_SUMMARY_LOCATION: path.resolve(__dirname, '../../downloads'),
  SCRAPED_WRITE_LOCATION: path.resolve(__dirname, '../../scraped'),
  SUMMARIES: {
    ['2022Q4']: '2022q4_form13f',
  },
}

export const FIDELITY_CONFIG = {
  THROTTLE: 100,
}

export const QUARTERLY_SUMMARY_FILE_NAMES = {
  COVERPAGE: 'COVERPAGE.tsv',
  INFOTABLE: 'INFOTABLE.tsv',
  OTHERMANAGER: 'OTHERMANAGER.tsv',
  OTHERMANAGER2: 'OTHERMANAGER2.tsv',
  SIGNATURE: 'SIGNATURE.tsv',
  SUBMISSION: 'SUBMISSION.tsv',
  SUMMARYPAGE: 'SUMMARYPAGE.tsv',
}

export const COLUMN_NAMES = {
  ACCESSION_NUMBER: 'ACCESSION_NUMBER',
  CIK: 'CIK',
  NAME: 'NAME',
  NAMEOFISSUER: 'NAMEOFISSUER',
  FILINGMANAGER_NAME: 'FILINGMANAGER_NAME',
  CUSIP: 'CUSIP',
}

export const COLUMN_WITH_NAME_INFO: Record<string, string> = {
  COVERPAGE: COLUMN_NAMES.FILINGMANAGER_NAME,
  INFOTABLE: COLUMN_NAMES.NAMEOFISSUER,
  OTHERMANAGER: COLUMN_NAMES.NAME,
  OTHERMANAGER2: COLUMN_NAMES.NAME,
}
